// Move finished games out of the live snapshot series and into the CLV archive.
//   npx tsx scripts/archive-odds.ts
//
// Runs right after each poll. A game that has kicked off can no longer change,
// so its snapshots are replayed once, boiled down to a resolution record, and
// dropped from the live history. That keeps oddsHistory.ts bounded while
// preserving the one thing worth keeping from a finished game: what the engine
// said, when it said it, and where the market closed.
//
// This uses the real engine rather than a reimplementation, so the grades can
// never drift from what the board actually showed.
import { readFileSync, writeFileSync } from 'fs';
import { oddsHistory } from '../src/nfl/data/oddsHistory';
import { clvArchive } from '../src/nfl/data/clvArchive';
import { sampleHistory } from '../src/nfl/data/sampleHistory';
import { sampleClv } from '../src/nfl/data/sampleClv';
import { resolveGame } from '../src/nfl/lib/clv';
import type { ResolvedGame, Snapshot } from '../src/nfl/types';

// `--sample` grades the synthetic weeks into the fixture archive. Live and
// sample data live in separate files precisely so neither can clobber the other.
const SAMPLE = process.argv.includes('--sample');
const HISTORY_OUT = SAMPLE ? 'src/nfl/data/sampleHistory.ts' : 'src/nfl/data/oddsHistory.ts';
const ARCHIVE_OUT = SAMPLE ? 'src/nfl/data/sampleClv.ts' : 'src/nfl/data/clvArchive.ts';
const HISTORY_SYM = SAMPLE ? 'sampleHistory' : 'oddsHistory';
const ARCHIVE_SYM = SAMPLE ? 'sampleClv' : 'clvArchive';
const sourceHistory = SAMPLE ? sampleHistory : oddsHistory;
const sourceArchive = SAMPLE ? sampleClv : clvArchive;

/** Only archive once a game is safely past kickoff and its line is final. */
const SETTLE_HOURS = 6;
/** Cap the archive so the committed file cannot grow without bound. */
const MAX_ARCHIVED = 600;

const now = Date.now();
const cutoff = now - SETTLE_HOURS * 3_600_000;

const snapshots: Snapshot[] = sourceHistory.snapshots;
if (snapshots.length === 0) {
  console.log('No snapshots to archive.');
  process.exit(0);
}

// Every game id currently in the live series, with its kickoff.
const kickoffs = new Map<string, string>();
for (const snap of snapshots) {
  for (const g of snap.games) kickoffs.set(g.id, g.commenceTime);
}

// Sample rows are scaffolding. The moment real games start arriving, drop
// them — mixing synthetic grades into a live track record would be worse than
// showing an empty one.
const priorHistory = readFileSync(HISTORY_OUT, 'utf8');
const fromSample = /GENERATED by scripts\/build-sample-odds/.test(priorHistory);
const keptGames = sourceArchive.sample && !fromSample ? [] : sourceArchive.games;
if (sourceArchive.sample && !fromSample) {
  console.log('Live data arrived — clearing sample rows from the archive.');
}

const already = new Set(keptGames.map((g) => g.id));
const toArchive = [...kickoffs.entries()]
  .filter(([id, commence]) => !already.has(id) && new Date(commence).getTime() < cutoff)
  .map(([id]) => id);

console.log(`${kickoffs.size} games in history, ${toArchive.length} ready to archive.`);

const resolved: ResolvedGame[] = [];
for (const id of toArchive) {
  const record = resolveGame(snapshots, id);
  if (!record) {
    console.log(`  skipped ${id} — could not replay`);
    continue;
  }
  const graded = [record.spread, record.total].filter((m) => m.clv !== null).length;
  console.log(
    `  archived ${record.awayTeam} @ ${record.homeTeam} — ` +
      `${record.spread.reads.length} polls, ${graded}/2 markets gradeable`
  );
  resolved.push(record);
}

if (resolved.length === 0 && toArchive.length === 0) {
  console.log('Nothing to do.');
  process.exit(0);
}

// --- Write the archive. ---
const archived = [...keptGames, ...resolved]
  .sort((a, b) => a.commenceTime.localeCompare(b.commenceTime))
  .slice(-MAX_ARCHIVED);

const archiveBanner =
  `// GENERATED by scripts/archive-odds.ts — do not edit by hand.\n` +
  `// ${archived.length} graded games.\n` +
  `import type { ClvArchive } from '../types';\n\n` +
  `export const ${ARCHIVE_SYM}: ClvArchive = `;

writeFileSync(
  ARCHIVE_OUT,
  `${archiveBanner}${JSON.stringify(
    { updatedAt: new Date().toISOString(), sample: fromSample, games: archived },
    null,
    2
  )};\n`
);

// --- Drop the archived games from the live series. ---
const archivedIds = new Set(resolved.map((g) => g.id));
const trimmed = snapshots
  .map((s) => ({ ...s, games: s.games.filter((g) => !archivedIds.has(g.id)) }))
  .filter((s) => s.games.length > 0);

// Preserve the generated banner's shape; only the payload changes.
const historyBanner = fromSample
  ? `// GENERATED by scripts/build-sample-odds.ts — SYNTHETIC SAMPLE DATA.\n` +
    `// Not real odds. Exists so the UI is explorable before ODDS_API_KEY is set;\n` +
    `// the first live poll from build-odds.mjs overwrites this file.\n` +
    `import type { OddsHistory } from '../types';\n\n` +
    `export const ${HISTORY_SYM}: OddsHistory = `
  : `// GENERATED by scripts/build-odds.mjs — do not edit by hand.\n` +
    `// ${trimmed.length} snapshots, latest ${sourceHistory.updatedAt}.\n` +
    `import type { OddsHistory } from '../types';\n\n` +
    `export const ${HISTORY_SYM}: OddsHistory = `;

writeFileSync(
  HISTORY_OUT,
  `${historyBanner}${JSON.stringify({ ...sourceHistory, snapshots: trimmed }, null, 2)};\n`
);

console.log(
  `Archive now holds ${archived.length} games; live history trimmed to ` +
    `${trimmed.length} snapshots.`
);
