// Regrade every archived game from its original snapshots.
//   npx tsx scripts/rebuild-archive.ts [--dry-run]
//
// The archive stores what the engine said at the time, in the engine's own
// numbers. When the pricing model changes those numbers are stale: the first
// live week was graded with a model that ignored pushes, which misread every
// line sitting on 3 or 7. Archived games are trimmed out of the live history,
// but every poll is still in git, so this walks each committed revision of
// oddsHistory.ts, reassembles the full snapshot series, and replays it through
// the current engine.
import { execFileSync } from 'child_process';
import { writeFileSync } from 'fs';
import { clvArchive } from '../src/nfl/data/clvArchive';
import { resolveGame, summarize } from '../src/nfl/lib/clv';
import { STRONG_MIN } from '../src/nfl/lib/sharp';
import type { GameQuote, OddsHistory, ResolvedGame, Snapshot } from '../src/nfl/types';

const PATH = 'src/nfl/data/oddsHistory.ts';
const MARKER = 'export const oddsHistory: OddsHistory = ';
const DRY = process.argv.includes('--dry-run');

const git = (...args: string[]) =>
  execFileSync('git', args, { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });

const revs = git('log', '--format=%H', '--', PATH).split('\n').filter(Boolean);
const byTime = new Map<string, Map<string, GameQuote>>();

for (const rev of revs) {
  const text = git('show', `${rev}:${PATH}`);
  const at = text.indexOf(MARKER);
  if (at === -1) continue;
  const parsed = JSON.parse(text.slice(at + MARKER.length, text.lastIndexOf('}') + 1)) as OddsHistory;
  // Early revisions of this file held the synthetic fixture.
  if (parsed.sample) continue;
  for (const snap of parsed.snapshots) {
    const games = byTime.get(snap.takenAt) ?? new Map<string, GameQuote>();
    for (const g of snap.games) if (!games.has(g.id)) games.set(g.id, g);
    byTime.set(snap.takenAt, games);
  }
}

const snapshots: Snapshot[] = [...byTime.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([takenAt, games]) => ({ takenAt, games: [...games.values()] }));
console.log(`${revs.length} revisions → ${snapshots.length} distinct polls`);

// Regrade exactly the games already archived; anything still live stays live.
const regraded: ResolvedGame[] = [];
for (const old of clvArchive.games) {
  const fresh = resolveGame(snapshots, old.id);
  if (!fresh) {
    console.log(`  kept as-is ${old.awayTeam} @ ${old.homeTeam} — snapshots not recoverable`);
    regraded.push(old);
    continue;
  }
  regraded.push(fresh);
}

const before = summarize(clvArchive, STRONG_MIN).overall;
const after = summarize({ ...clvArchive, games: regraded }, STRONG_MIN).overall;
const line = (o: typeof before) =>
  `${o.n} flags, mean CLV ${o.meanClv.toFixed(2)}, ` +
  `beat ${Math.round(o.beatRate * 100)}%`;
console.log(`before: ${line(before)}`);
console.log(`after:  ${line(after)}`);

if (DRY) process.exit(0);

const banner =
  `// GENERATED by scripts/archive-odds.ts — do not edit by hand.\n` +
  `// ${regraded.length} graded games.\n` +
  `import type { ClvArchive } from '../types';\n\n` +
  `export const clvArchive: ClvArchive = `;
writeFileSync(
  'src/nfl/data/clvArchive.ts',
  `${banner}${JSON.stringify({ ...clvArchive, updatedAt: new Date().toISOString(), games: regraded }, null, 2)};\n`
);
console.log(`Rewrote clvArchive.ts with ${regraded.length} regraded games.`);
