// GENERATED by scripts/archive-odds.ts — do not edit by hand.
// 14 graded games.
import type { ClvArchive } from '../types';

export const clvArchive: ClvArchive = {
  "updatedAt": "2026-09-21T17:55:47.951Z",
  "sample": false,
  "games": [
    {
      "id": "9d14f87600f6edc74dbcb5c74edf6246",
      "commenceTime": "2026-09-20T17:02:22Z",
      "homeTeam": "New England Patriots",
      "awayTeam": "Pittsburgh Steelers",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 1.2476404483797054,
            "side": "away",
            "mu": 5.363618152248593,
            "line": -5.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 4.917736273914647,
            "side": "away",
            "mu": 5.324446896812044,
            "line": -5.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 4.917736273914647,
            "side": "away",
            "mu": 5.324446896812044,
            "line": -5.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 5.196629785207119,
            "side": "away",
            "mu": 5.168113504447094,
            "line": -5.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 5.196629785207119,
            "side": "away",
            "mu": 5.168113504447094,
            "line": -5.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 28.978845566545782,
            "side": "away",
            "mu": 4.621303747475322,
            "line": -5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 44.04097789599318,
            "side": "away",
            "mu": 4.376235506961168,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 44.04097789599318,
            "side": "away",
            "mu": 4.376235506961168,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 44.04097789599318,
            "side": "away",
            "mu": 4.376235506961168,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 44.04097789599318,
            "side": "away",
            "mu": 4.376235506961168,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 44.04097789599318,
            "side": "away",
            "mu": 4.376235506961168,
            "line": -4.5
          }
        ],
        "closingMu": 4.376235506961168,
        "closingLine": -4.5,
        "flaggedAt": "2026-09-20T16:08:44.964Z",
        "flaggedSide": "away",
        "flaggedScore": 28.978845566545782,
        "flaggedMu": 4.621303747475322,
        "flaggedLine": -5,
        "clv": 0.2450682405141542
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 3.4189341459126865,
            "side": "under",
            "mu": 41.22052032212417,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 5.589593557516537,
            "side": "under",
            "mu": 41.22052032212417,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 5.589593557516537,
            "side": "under",
            "mu": 41.22052032212417,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0.2526544282189034,
            "side": "over",
            "mu": 41.293952093606805,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0.2526544282189034,
            "side": "over",
            "mu": 41.293952093606805,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 3.4812985460619923,
            "side": "over",
            "mu": 41.30840351640141,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 2.635808028514162,
            "side": "under",
            "mu": 41.17274346266202,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 2.635808028514162,
            "side": "under",
            "mu": 41.17274346266202,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 2.635808028514162,
            "side": "under",
            "mu": 41.17274346266202,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 2.635808028514162,
            "side": "under",
            "mu": 41.17274346266202,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 2.635808028514162,
            "side": "under",
            "mu": 41.17274346266202,
            "line": 41.5
          }
        ],
        "closingMu": 41.17274346266202,
        "closingLine": 41.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "2143ade9684fd876b68a4e8cbf451f05",
      "commenceTime": "2026-09-20T17:02:38Z",
      "homeTeam": "Baltimore Ravens",
      "awayTeam": "New Orleans Saints",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 2.640876898201121,
            "side": "home",
            "mu": 8.266731866915256,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0.4106236122574458,
            "side": "home",
            "mu": 8.266731866915256,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0.4106236122574458,
            "side": "home",
            "mu": 8.266731866915256,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 4.919061089893989,
            "side": "away",
            "mu": 8.117284555792846,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 4.919061089893989,
            "side": "away",
            "mu": 8.117284555792846,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 0.7481688677328613,
            "side": "home",
            "mu": 8.22887770630589,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 12.227299919708054,
            "side": "away",
            "mu": 7.9949444537400165,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 12.227299919708054,
            "side": "away",
            "mu": 7.9949444537400165,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 12.227299919708054,
            "side": "away",
            "mu": 7.9949444537400165,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 12.227299919708054,
            "side": "away",
            "mu": 7.9949444537400165,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 12.227299919708054,
            "side": "away",
            "mu": 7.9949444537400165,
            "line": -9
          }
        ],
        "closingMu": 7.9949444537400165,
        "closingLine": -9,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0,
            "side": null,
            "mu": 45.5,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0,
            "side": null,
            "mu": 45.5,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0,
            "side": null,
            "mu": 45.5,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0,
            "side": null,
            "mu": 45.5,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0,
            "side": null,
            "mu": 45.5,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 28.229993951275908,
            "side": "under",
            "mu": 44.9603754354752,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 23.10753339815001,
            "side": "under",
            "mu": 45.078948239872744,
            "line": 45.25
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 23.10753339815001,
            "side": "under",
            "mu": 45.078948239872744,
            "line": 45.25
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 23.10753339815001,
            "side": "under",
            "mu": 45.078948239872744,
            "line": 45.25
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 23.10753339815001,
            "side": "under",
            "mu": 45.078948239872744,
            "line": 45.25
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 23.10753339815001,
            "side": "under",
            "mu": 45.078948239872744,
            "line": 45.25
          }
        ],
        "closingMu": 45.078948239872744,
        "closingLine": 45.25,
        "flaggedAt": "2026-09-20T16:08:44.964Z",
        "flaggedSide": "under",
        "flaggedScore": 28.229993951275908,
        "flaggedMu": 44.9603754354752,
        "flaggedLine": 45,
        "clv": -0.11857280439754447
      }
    },
    {
      "id": "0283a29e1b38ef78b29b904fd56a16dd",
      "commenceTime": "2026-09-20T17:02:38Z",
      "homeTeam": "Chicago Bears",
      "awayTeam": "Minnesota Vikings",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 1.636649628259761,
            "side": "away",
            "mu": 4.418167518587012,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 3.3964372924684696,
            "side": "away",
            "mu": 4.385491423935739,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 8.301833548017703,
            "side": "away",
            "mu": 4.300641492208924,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0.37896677493566955,
            "side": "home",
            "mu": 4.458479846650921,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0.636219801301845,
            "side": "away",
            "mu": 4.43817611512617,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 14.939200470017031,
            "side": "away",
            "mu": 4.197180072421098,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 14.939200470017031,
            "side": "away",
            "mu": 4.197180072421098,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 14.939200470017031,
            "side": "away",
            "mu": 4.197180072421098,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 14.939200470017031,
            "side": "away",
            "mu": 4.197180072421098,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 14.939200470017031,
            "side": "away",
            "mu": 4.197180072421098,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 14.939200470017031,
            "side": "away",
            "mu": 4.197180072421098,
            "line": -4.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 14.939200470017031,
            "side": "away",
            "mu": 4.197180072421098,
            "line": -4.5
          }
        ],
        "closingMu": 4.197180072421098,
        "closingLine": -4.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 4.567851628330146,
            "side": "under",
            "mu": 47,
            "line": 47
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 4.567851628330146,
            "side": "under",
            "mu": 47,
            "line": 47
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 4.567851628330146,
            "side": "under",
            "mu": 47,
            "line": 47
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 9.115606768187845,
            "side": "under",
            "mu": 46.92449627881861,
            "line": 47
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 9.115606768187845,
            "side": "under",
            "mu": 46.92449627881861,
            "line": 47
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 3.285551035221701,
            "side": "under",
            "mu": 46.85667951956953,
            "line": 47
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 2.81741078065813,
            "side": "under",
            "mu": 46.5542664852901,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 2.81741078065813,
            "side": "under",
            "mu": 46.5542664852901,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 2.81741078065813,
            "side": "under",
            "mu": 46.5542664852901,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 2.81741078065813,
            "side": "under",
            "mu": 46.5542664852901,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 2.81741078065813,
            "side": "under",
            "mu": 46.5542664852901,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 2.81741078065813,
            "side": "under",
            "mu": 46.5542664852901,
            "line": 46.5
          }
        ],
        "closingMu": 46.5542664852901,
        "closingLine": 46.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "36ad2fa722f4915ef23d2c81351261de",
      "commenceTime": "2026-09-20T17:02:38Z",
      "homeTeam": "Houston Texans",
      "awayTeam": "Cincinnati Bengals",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 2.181024147227131,
            "side": "home",
            "mu": 2.8250660697531105,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 2.181024147227131,
            "side": "home",
            "mu": 2.8250660697531105,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 2.181024147227131,
            "side": "home",
            "mu": 2.8250660697531105,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 2.181024147227131,
            "side": "home",
            "mu": 2.8250660697531105,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 2.181024147227131,
            "side": "home",
            "mu": 2.8250660697531105,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 5.5748242590434405,
            "side": "away",
            "mu": 2.737242093636663,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 4.411074599046083,
            "side": "home",
            "mu": 2.7490204502679134,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 4.411074599046083,
            "side": "home",
            "mu": 2.7490204502679134,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 4.411074599046083,
            "side": "home",
            "mu": 2.7490204502679134,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 4.411074599046083,
            "side": "home",
            "mu": 2.7490204502679134,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 4.411074599046083,
            "side": "home",
            "mu": 2.7490204502679134,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 4.411074599046083,
            "side": "home",
            "mu": 2.7490204502679134,
            "line": -2.75
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 4.411074599046083,
            "side": "home",
            "mu": 2.7490204502679134,
            "line": -2.75
          }
        ],
        "closingMu": 2.7490204502679134,
        "closingLine": -2.75,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0.04268517061717603,
            "side": "under",
            "mu": 45.417033697422866,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 1.4657536045103303,
            "side": "under",
            "mu": 45.38913649944389,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 1.4657536045103303,
            "side": "under",
            "mu": 45.38913649944389,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 1.4657536045103303,
            "side": "under",
            "mu": 45.38913649944389,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 1.4657536045103303,
            "side": "under",
            "mu": 45.38913649944389,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 1.62931344958417,
            "side": "under",
            "mu": 45.38599451661243,
            "line": 45.5
          }
        ],
        "closingMu": 45.38599451661243,
        "closingLine": 45.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "0636ebff776d43f8c829a36713c80b22",
      "commenceTime": "2026-09-20T17:02:40Z",
      "homeTeam": "Tampa Bay Buccaneers",
      "awayTeam": "Cleveland Browns",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 1.5833703861667914,
            "side": "home",
            "mu": 8.153168344640758,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 1.5833703861667914,
            "side": "home",
            "mu": 8.153168344640758,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 1.5833703861667914,
            "side": "home",
            "mu": 8.153168344640758,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 7.879785343889652,
            "side": "home",
            "mu": 8.264761495153802,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 7.879785343889652,
            "side": "home",
            "mu": 8.264761495153802,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 1.1872481858990902,
            "side": "home",
            "mu": 8.115645970502436,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 10.652203161498797,
            "side": "away",
            "mu": 7.861843228718393,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 10.652203161498797,
            "side": "away",
            "mu": 7.861843228718393,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 10.652203161498797,
            "side": "away",
            "mu": 7.861843228718393,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 10.652203161498797,
            "side": "away",
            "mu": 7.861843228718393,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 10.652203161498797,
            "side": "away",
            "mu": 7.861843228718393,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 10.652203161498797,
            "side": "away",
            "mu": 7.861843228718393,
            "line": -9
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 10.652203161498797,
            "side": "away",
            "mu": 7.861843228718393,
            "line": -9
          }
        ],
        "closingMu": 7.861843228718393,
        "closingLine": -9,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 2.807505754306021,
            "side": "over",
            "mu": 41.45167691321893,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 2.807505754306021,
            "side": "over",
            "mu": 41.45167691321893,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 2.807505754306021,
            "side": "over",
            "mu": 41.45167691321893,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 2.807505754306021,
            "side": "over",
            "mu": 41.45167691321893,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 2.807505754306021,
            "side": "over",
            "mu": 41.45167691321893,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 5.185081864856892,
            "side": "over",
            "mu": 41.46409396506687,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 3.796939495034318,
            "side": "over",
            "mu": 41.5,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 3.796939495034318,
            "side": "over",
            "mu": 41.5,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 3.796939495034318,
            "side": "over",
            "mu": 41.5,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 3.796939495034318,
            "side": "over",
            "mu": 41.5,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 3.796939495034318,
            "side": "over",
            "mu": 41.5,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 3.796939495034318,
            "side": "over",
            "mu": 41.5,
            "line": 41.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 3.796939495034318,
            "side": "over",
            "mu": 41.5,
            "line": 41.5
          }
        ],
        "closingMu": 41.5,
        "closingLine": 41.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "fafc649c455e32a0f2ba1bd06e2039bc",
      "commenceTime": "2026-09-20T17:02:50Z",
      "homeTeam": "Tennessee Titans",
      "awayTeam": "Philadelphia Eagles",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 3.2844267187344833,
            "side": "home",
            "mu": -6.981755509493638,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 6.8826315034856895,
            "side": "home",
            "mu": -6.919320837113301,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 6.8826315034856895,
            "side": "home",
            "mu": -6.919320837113301,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 2.125247564895947,
            "side": "away",
            "mu": -7.100982894411446,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 2.125247564895947,
            "side": "away",
            "mu": -7.100982894411446,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 40.574570461011625,
            "side": "home",
            "mu": -6.746541821667361,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 51.663676952454836,
            "side": "home",
            "mu": -6.504473649958451,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 51.663676952454836,
            "side": "home",
            "mu": -6.504473649958451,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 51.663676952454836,
            "side": "home",
            "mu": -6.504473649958451,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 51.663676952454836,
            "side": "home",
            "mu": -6.504473649958451,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 51.663676952454836,
            "side": "home",
            "mu": -6.504473649958451,
            "line": 7
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 51.663676952454836,
            "side": "home",
            "mu": -6.504473649958451,
            "line": 7
          }
        ],
        "closingMu": -6.504473649958451,
        "closingLine": 7,
        "flaggedAt": "2026-09-20T16:08:44.964Z",
        "flaggedSide": "home",
        "flaggedScore": 40.574570461011625,
        "flaggedMu": -6.746541821667361,
        "flaggedLine": 7,
        "clv": 0.24206817170891082
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 1.081741683145765,
            "side": "over",
            "mu": 39.66262005473748,
            "line": 39.75
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0.4655501239961663,
            "side": "under",
            "mu": 39.53583541998944,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0.4655501239961663,
            "side": "under",
            "mu": 39.53583541998944,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0.4655501239961663,
            "side": "under",
            "mu": 39.53583541998944,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0.4655501239961663,
            "side": "under",
            "mu": 39.53583541998944,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 1.1975886057587797,
            "side": "under",
            "mu": 39.507535962588356,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 1.1975886057587797,
            "side": "under",
            "mu": 39.507535962588356,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 1.1975886057587797,
            "side": "under",
            "mu": 39.507535962588356,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 1.1975886057587797,
            "side": "under",
            "mu": 39.507535962588356,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 1.1975886057587797,
            "side": "under",
            "mu": 39.507535962588356,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 1.1975886057587797,
            "side": "under",
            "mu": 39.507535962588356,
            "line": 39.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 1.1975886057587797,
            "side": "under",
            "mu": 39.507535962588356,
            "line": 39.5
          }
        ],
        "closingMu": 39.507535962588356,
        "closingLine": 39.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "aee7eae1849ebb103b9bf233e9741392",
      "commenceTime": "2026-09-20T17:02:58Z",
      "homeTeam": "Atlanta Falcons",
      "awayTeam": "Carolina Panthers",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0.7923726410610588,
            "side": "away",
            "mu": -3.0446128597138413,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0.8197769839669,
            "side": "home",
            "mu": -3.0446128597138413,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0.8197769839669,
            "side": "home",
            "mu": -3.0446128597138413,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 1.1069433241311843,
            "side": "away",
            "mu": -3.083147265875803,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 1.1069433241311843,
            "side": "away",
            "mu": -3.083147265875803,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 28.925474141051183,
            "side": "home",
            "mu": -2.7212823932355525,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 48.59113023762542,
            "side": "home",
            "mu": -2.2703038889665983,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 48.59113023762542,
            "side": "home",
            "mu": -2.2703038889665983,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 48.59113023762542,
            "side": "home",
            "mu": -2.2703038889665983,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 48.59113023762542,
            "side": "home",
            "mu": -2.2703038889665983,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 48.59113023762542,
            "side": "home",
            "mu": -2.2703038889665983,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 48.59113023762542,
            "side": "home",
            "mu": -2.2703038889665983,
            "line": 2.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 48.59113023762542,
            "side": "home",
            "mu": -2.2703038889665983,
            "line": 2.5
          }
        ],
        "closingMu": -2.2703038889665983,
        "closingLine": 2.5,
        "flaggedAt": "2026-09-20T16:08:44.964Z",
        "flaggedSide": "home",
        "flaggedScore": 28.925474141051183,
        "flaggedMu": -2.7212823932355525,
        "flaggedLine": 2.5,
        "clv": 0.45097850426895425
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0.5739963457406816,
            "side": "under",
            "mu": 43.471300182712966,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0.5739963457406816,
            "side": "under",
            "mu": 43.471300182712966,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0.5739963457406816,
            "side": "under",
            "mu": 43.471300182712966,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0.5739963457406816,
            "side": "under",
            "mu": 43.471300182712966,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0.5739963457406816,
            "side": "under",
            "mu": 43.471300182712966,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 0.5739963457406816,
            "side": "under",
            "mu": 43.471300182712966,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 3.342933823699852,
            "side": "under",
            "mu": 43.33366368245604,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 3.342933823699852,
            "side": "under",
            "mu": 43.33366368245604,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 3.342933823699852,
            "side": "under",
            "mu": 43.33366368245604,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 3.342933823699852,
            "side": "under",
            "mu": 43.33366368245604,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 3.342933823699852,
            "side": "under",
            "mu": 43.33366368245604,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 3.342933823699852,
            "side": "under",
            "mu": 43.33366368245604,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 3.342933823699852,
            "side": "under",
            "mu": 43.33366368245604,
            "line": 43.5
          }
        ],
        "closingMu": 43.33366368245604,
        "closingLine": 43.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "4aeee070bb6ec60bdfae4dede61b9014",
      "commenceTime": "2026-09-20T17:03:51Z",
      "homeTeam": "New York Jets",
      "awayTeam": "Green Bay Packers",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 4.119656982591016,
            "side": "away",
            "mu": -3.631983023797133,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 4.119656982591016,
            "side": "away",
            "mu": -3.631983023797133,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 4.119656982591016,
            "side": "away",
            "mu": -3.631983023797133,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0.39609554086754706,
            "side": "home",
            "mu": -3.4251431122630107,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0.39609554086754706,
            "side": "home",
            "mu": -3.4251431122630107,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 12.052904976455379,
            "side": "home",
            "mu": -3.1381317147491723,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 23.828159176375195,
            "side": "home",
            "mu": -3.1174892745117826,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 23.828159176375195,
            "side": "home",
            "mu": -3.1174892745117826,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 23.828159176375195,
            "side": "home",
            "mu": -3.1174892745117826,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 23.828159176375195,
            "side": "home",
            "mu": -3.1174892745117826,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 23.828159176375195,
            "side": "home",
            "mu": -3.1174892745117826,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 23.828159176375195,
            "side": "home",
            "mu": -3.1174892745117826,
            "line": 3
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 23.828159176375195,
            "side": "home",
            "mu": -3.1174892745117826,
            "line": 3
          }
        ],
        "closingMu": -3.1174892745117826,
        "closingLine": 3,
        "flaggedAt": "2026-09-20T16:54:04.223Z",
        "flaggedSide": "home",
        "flaggedScore": 23.828159176375195,
        "flaggedMu": -3.1174892745117826,
        "flaggedLine": 3,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 3.5099583242376298,
            "side": "under",
            "mu": 44.13580370929175,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 3.5099583242376298,
            "side": "under",
            "mu": 44.13580370929175,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 3.5099583242376298,
            "side": "under",
            "mu": 44.13580370929175,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 16.827344794065898,
            "side": "under",
            "mu": 43.92449627881861,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 16.827344794065898,
            "side": "under",
            "mu": 43.92449627881861,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 12.259885836118704,
            "side": "under",
            "mu": 43.969583995810915,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 15.191629773621754,
            "side": "under",
            "mu": 43.92559363144126,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 15.191629773621754,
            "side": "under",
            "mu": 43.92559363144126,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 15.191629773621754,
            "side": "under",
            "mu": 43.92559363144126,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 15.191629773621754,
            "side": "under",
            "mu": 43.92559363144126,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 15.191629773621754,
            "side": "under",
            "mu": 43.92559363144126,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 15.191629773621754,
            "side": "under",
            "mu": 43.92559363144126,
            "line": 44
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 15.191629773621754,
            "side": "under",
            "mu": 43.92559363144126,
            "line": 44
          }
        ],
        "closingMu": 43.92559363144126,
        "closingLine": 44,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "71b3b83747589efdc5baef2c5cf811bf",
      "commenceTime": "2026-09-20T20:05:18Z",
      "homeTeam": "Los Angeles Chargers",
      "awayTeam": "Las Vegas Raiders",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 2.089763931849724,
            "side": "away",
            "mu": 6.760823781402309,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 2.089763931849724,
            "side": "away",
            "mu": 6.760823781402309,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 2.089763931849724,
            "side": "away",
            "mu": 6.760823781402309,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 5.506474597354227,
            "side": "away",
            "mu": 6.699358507791078,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 5.506474597354227,
            "side": "away",
            "mu": 6.699358507791078,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 3.2603197219080773,
            "side": "home",
            "mu": 6.867656767058973,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 8.557676824673516,
            "side": "home",
            "mu": 6.9437686461462125,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 11.08541646919555,
            "side": "home",
            "mu": 6.984873920980796,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 11.08541646919555,
            "side": "home",
            "mu": 6.984873920980796,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 4.382566898022552,
            "side": "away",
            "mu": 6.719078531367062,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 3.14799415711942,
            "side": "away",
            "mu": 6.741290519416923,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 3.14799415711942,
            "side": "away",
            "mu": 6.741290519416923,
            "line": -6.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 3.14799415711942,
            "side": "away",
            "mu": 6.741290519416923,
            "line": -6.5
          }
        ],
        "closingMu": 6.741290519416923,
        "closingLine": -6.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 1.7027297556023768,
            "side": "under",
            "mu": 43.41486351221988,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 2.5084606449639786,
            "side": "under",
            "mu": 43.399767801049066,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 2.5084606449639786,
            "side": "under",
            "mu": 43.399767801049066,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 1.7027297556023768,
            "side": "under",
            "mu": 43.41486351221988,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 1.7027297556023768,
            "side": "under",
            "mu": 43.41486351221988,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 0.5955617802963786,
            "side": "over",
            "mu": 43.460829342937856,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 2.5540946334035652,
            "side": "over",
            "mu": 43.5,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 2.5540946334035652,
            "side": "over",
            "mu": 43.5,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 2.5540946334035652,
            "side": "over",
            "mu": 43.5,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 2.5540946334035652,
            "side": "over",
            "mu": 43.5,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 1.0105945089026136,
            "side": "over",
            "mu": 43.46912999750998,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 1.0105945089026136,
            "side": "over",
            "mu": 43.46912999750998,
            "line": 43.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 1.0105945089026136,
            "side": "over",
            "mu": 43.46912999750998,
            "line": 43.5
          }
        ],
        "closingMu": 43.46912999750998,
        "closingLine": 43.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "1fd6628c781f556a7a19638e97d7107f",
      "commenceTime": "2026-09-20T20:05:33Z",
      "homeTeam": "Denver Broncos",
      "awayTeam": "Jacksonville Jaguars",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 1.591909052450271,
            "side": "home",
            "mu": 3.2298644436879114,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 1.591909052450271,
            "side": "home",
            "mu": 3.2298644436879114,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 1.591909052450271,
            "side": "home",
            "mu": 3.2298644436879114,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 1.7433638572038168,
            "side": "home",
            "mu": 3.2070266269216963,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 1.7433638572038168,
            "side": "home",
            "mu": 3.2070266269216963,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 1.9797238255446548,
            "side": "home",
            "mu": 3.211753826288513,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 3.3106029668410564,
            "side": "home",
            "mu": 3.150255516747486,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 2.3923289973909334,
            "side": "home",
            "mu": 3.1318900373584837,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 2.3923289973909334,
            "side": "home",
            "mu": 3.1318900373584837,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 2.3885734116076964,
            "side": "away",
            "mu": 3.150255516747486,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 1.9101688089317914,
            "side": "away",
            "mu": 3.045840081232029,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 1.9101688089317914,
            "side": "away",
            "mu": 3.045840081232029,
            "line": -2.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 1.9101688089317914,
            "side": "away",
            "mu": 3.045840081232029,
            "line": -2.5
          }
        ],
        "closingMu": 3.045840081232029,
        "closingLine": -2.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 4.12284762380537,
            "side": "over",
            "mu": 45.651123923694044,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 4.12284762380537,
            "side": "over",
            "mu": 45.651123923694044,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 4.12284762380537,
            "side": "over",
            "mu": 45.651123923694044,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 3.0224784738808808,
            "side": "over",
            "mu": 45.651123923694044,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 3.0224784738808808,
            "side": "over",
            "mu": 45.651123923694044,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 3.887231881566824,
            "side": "over",
            "mu": 45.66667371178177,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 5.899448607430195,
            "side": "over",
            "mu": 45.681769422952584,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 6.5568397085006,
            "side": "over",
            "mu": 45.71294598948317,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 6.5568397085006,
            "side": "over",
            "mu": 45.71294598948317,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 4.742309487862387,
            "side": "over",
            "mu": 45.681769422952584,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 5.599970204613118,
            "side": "over",
            "mu": 45.69664570290735,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 5.599970204613118,
            "side": "over",
            "mu": 45.69664570290735,
            "line": 45.5
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 5.599970204613118,
            "side": "over",
            "mu": 45.69664570290735,
            "line": 45.5
          }
        ],
        "closingMu": 45.69664570290735,
        "closingLine": 45.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "4dd8020192a544385db42374e5555303",
      "commenceTime": "2026-09-20T20:28:00Z",
      "homeTeam": "Arizona Cardinals",
      "awayTeam": "Seattle Seahawks",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 4.568545229185554,
            "side": "home",
            "mu": -3.6213037474753245,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 4.568545229185554,
            "side": "home",
            "mu": -3.6213037474753245,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 4.568545229185554,
            "side": "home",
            "mu": -3.6213037474753245,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 4.568545229185554,
            "side": "home",
            "mu": -3.6213037474753245,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 4.568545229185554,
            "side": "home",
            "mu": -3.6213037474753245,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 4.888033659765043,
            "side": "home",
            "mu": -3.6157836213465515,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 7.921342901407155,
            "side": "home",
            "mu": -3.6157836213465515,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 7.180717630438136,
            "side": "home",
            "mu": -3.629167895876432,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 7.180717630438136,
            "side": "home",
            "mu": -3.629167895876432,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 4.083687222188024,
            "side": "home",
            "mu": -3.691108504041434,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 0.3917150620687293,
            "side": "home",
            "mu": -3.76494794724382,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 0.3917150620687293,
            "side": "home",
            "mu": -3.76494794724382,
            "line": 4
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 0.3917150620687293,
            "side": "home",
            "mu": -3.76494794724382,
            "line": 4
          }
        ],
        "closingMu": -3.76494794724382,
        "closingLine": 4,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0.0592069553729857,
            "side": "under",
            "mu": 40.99703965223135,
            "line": 40.75
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0.0592069553729857,
            "side": "under",
            "mu": 40.99703965223135,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0.0592069553729857,
            "side": "under",
            "mu": 40.99703965223135,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 1.1809688043916773,
            "side": "over",
            "mu": 41.05389063604812,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 1.1809688043916773,
            "side": "over",
            "mu": 41.05389063604812,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 1.8884822098012606,
            "side": "over",
            "mu": 41.08254257587363,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 1.5103255360855716,
            "side": "over",
            "mu": 41.08254257587363,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 1.5103255360855716,
            "side": "over",
            "mu": 41.08254257587363,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 1.5103255360855716,
            "side": "over",
            "mu": 41.08254257587363,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 1.5103255360855716,
            "side": "over",
            "mu": 41.08254257587363,
            "line": 41
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 2.6489984669816105,
            "side": "over",
            "mu": 41.04945796720825,
            "line": 40.75
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 0.2980992236065434,
            "side": "over",
            "mu": 41.00416578527886,
            "line": 40.75
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 0,
            "side": null,
            "mu": 41,
            "line": 41
          }
        ],
        "closingMu": 41,
        "closingLine": 41,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "85ef85098ddd22fe4ecf45e7e3c0a9c0",
      "commenceTime": "2026-09-20T20:28:00Z",
      "homeTeam": "Dallas Cowboys",
      "awayTeam": "Washington Commanders",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0.7514060877261919,
            "side": "away",
            "mu": 3.8121607045482926,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0.7514060877261919,
            "side": "away",
            "mu": 3.8121607045482926,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0.7514060877261919,
            "side": "away",
            "mu": 3.8121607045482926,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 2.276789402385724,
            "side": "away",
            "mu": 3.8121607045482926,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 3.7567859090341478,
            "side": "away",
            "mu": 3.8121607045482926,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 1.488307148867043,
            "side": "away",
            "mu": 3.911405488553715,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 0.45802543297589704,
            "side": "away",
            "mu": 3.932011122871538,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 1.488307148867043,
            "side": "away",
            "mu": 3.911405488553715,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 1.488307148867043,
            "side": "away",
            "mu": 3.911405488553715,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 5.931167893878877,
            "side": "away",
            "mu": 3.8121607045482926,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 4.105137505760861,
            "side": "away",
            "mu": 3.848681312310653,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 2.1465747339334174,
            "side": "away",
            "mu": 3.887852567747202,
            "line": -4
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 1.5028464018256615,
            "side": "home",
            "mu": 3.9608409904623834,
            "line": -4
          }
        ],
        "closingMu": 3.9608409904623834,
        "closingLine": -4,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 50.971300182712966,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 50.971300182712966,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 50.971300182712966,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 50.971300182712966,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 50.971300182712966,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 50.971300182712966,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 2.014529314244471,
            "side": "over",
            "mu": 51,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 2.014529314244471,
            "side": "over",
            "mu": 51,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 2.014529314244471,
            "side": "over",
            "mu": 51,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 2.014529314244471,
            "side": "over",
            "mu": 51,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 6.925128400467386,
            "side": "over",
            "mu": 51.11086350055611,
            "line": 51
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 43.71566660129075,
            "side": "over",
            "mu": 51.68829099035928,
            "line": 51.75
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 37.51149514797336,
            "side": "over",
            "mu": 51.68829099035928,
            "line": 52
          }
        ],
        "closingMu": 51.68829099035928,
        "closingLine": 52,
        "flaggedAt": "2026-09-20T20:12:55.494Z",
        "flaggedSide": "over",
        "flaggedScore": 43.71566660129075,
        "flaggedMu": 51.68829099035928,
        "flaggedLine": 51.75,
        "clv": 0
      }
    },
    {
      "id": "68bc55903f50af4af4766adcc89fcc61",
      "commenceTime": "2026-09-20T20:28:00Z",
      "homeTeam": "San Francisco 49ers",
      "awayTeam": "Miami Dolphins",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 3.2117085761633746,
            "side": "away",
            "mu": 13.339414571191831,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 3.2117085761633746,
            "side": "away",
            "mu": 13.339414571191831,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 3.2117085761633746,
            "side": "away",
            "mu": 13.339414571191831,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 6.076928372704398,
            "side": "away",
            "mu": 13.289232555816348,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 6.076928372704398,
            "side": "away",
            "mu": 13.289232555816348,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 2.3402816425011075,
            "side": "away",
            "mu": 13.210718318667157,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 7.347953834170742,
            "side": "away",
            "mu": 13.210718318667157,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 7.347953834170742,
            "side": "away",
            "mu": 13.210718318667157,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 7.347953834170742,
            "side": "away",
            "mu": 13.210718318667157,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 7.347953834170742,
            "side": "away",
            "mu": 13.210718318667157,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 42.516727889160535,
            "side": "away",
            "mu": 12.82011723003686,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 38.51937728651927,
            "side": "away",
            "mu": 12.783451659615924,
            "line": -13
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 37.17507165308035,
            "side": "away",
            "mu": 12.783451659615924,
            "line": -13
          }
        ],
        "closingMu": 12.783451659615924,
        "closingLine": -13,
        "flaggedAt": "2026-09-20T19:51:04.824Z",
        "flaggedSide": "away",
        "flaggedScore": 42.516727889160535,
        "flaggedMu": 12.82011723003686,
        "flaggedLine": -13,
        "clv": 0.03666557042093643
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 0,
            "side": null,
            "mu": 45,
            "line": 45
          }
        ],
        "closingMu": 45,
        "closingLine": 45,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      }
    },
    {
      "id": "50bc247030707d823b9c3581d7eb5760",
      "commenceTime": "2026-09-21T00:20:00Z",
      "homeTeam": "Kansas City Chiefs",
      "awayTeam": "Indianapolis Colts",
      "spread": {
        "market": "spread",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 3.936235581454533,
            "side": "away",
            "mu": 5.655065302679393,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 5.135273498732865,
            "side": "away",
            "mu": 5.634150943439883,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 5.135273498732865,
            "side": "away",
            "mu": 5.634150943439883,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 3.936235581454533,
            "side": "away",
            "mu": 5.655065302679393,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 3.936235581454533,
            "side": "away",
            "mu": 5.655065302679393,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 3.936235581454533,
            "side": "away",
            "mu": 5.655065302679393,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 7.429901259239691,
            "side": "away",
            "mu": 5.595479889821801,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 7.429901259239691,
            "side": "away",
            "mu": 5.595479889821801,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 7.429901259239691,
            "side": "away",
            "mu": 5.595479889821801,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 7.429901259239691,
            "side": "away",
            "mu": 5.595479889821801,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 5.886418202054492,
            "side": "away",
            "mu": 5.621303747475322,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 5.886418202054492,
            "side": "away",
            "mu": 5.621303747475322,
            "line": -6
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 5.886418202054492,
            "side": "away",
            "mu": 5.621303747475322,
            "line": -6
          },
          {
            "takenAt": "2026-09-21T00:04:40.184Z",
            "score": 6.913181799572896,
            "side": "away",
            "mu": 5.55573780931325,
            "line": -5.5
          }
        ],
        "closingMu": 5.55573780931325,
        "closingLine": -5.5,
        "flaggedAt": null,
        "flaggedSide": null,
        "flaggedScore": 0,
        "flaggedMu": null,
        "flaggedLine": null,
        "clv": null
      },
      "total": {
        "market": "total",
        "reads": [
          {
            "takenAt": "2026-09-20T13:43:19.187Z",
            "score": 2.8967999995211358,
            "side": "over",
            "mu": 46.20944839483688,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T14:01:11.908Z",
            "score": 2.8967999995211358,
            "side": "over",
            "mu": 46.20944839483688,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T14:01:43.290Z",
            "score": 2.8967999995211358,
            "side": "over",
            "mu": 46.20944839483688,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T15:15:38.913Z",
            "score": 2.8967999995211358,
            "side": "over",
            "mu": 46.20944839483688,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T15:18:19.493Z",
            "score": 2.8967999995211358,
            "side": "over",
            "mu": 46.20944839483688,
            "line": 46.5
          },
          {
            "takenAt": "2026-09-20T16:08:44.964Z",
            "score": 1.1868705310968153,
            "side": "over",
            "mu": 46.12395192141567,
            "line": 46.25
          },
          {
            "takenAt": "2026-09-20T16:54:04.223Z",
            "score": 1.1749432881456132,
            "side": "under",
            "mu": 45.90609409774424,
            "line": 46.25
          },
          {
            "takenAt": "2026-09-20T17:48:23.552Z",
            "score": 1.1749432881456132,
            "side": "under",
            "mu": 45.90609409774424,
            "line": 46.25
          },
          {
            "takenAt": "2026-09-20T17:50:35.498Z",
            "score": 1.1749432881456132,
            "side": "under",
            "mu": 45.90609409774424,
            "line": 46.25
          },
          {
            "takenAt": "2026-09-20T18:35:10.659Z",
            "score": 1.1749432881456132,
            "side": "under",
            "mu": 45.90609409774424,
            "line": 46.25
          },
          {
            "takenAt": "2026-09-20T19:51:04.824Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 45.971300182712966,
            "line": 46
          },
          {
            "takenAt": "2026-09-20T20:12:55.494Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 45.971300182712966,
            "line": 46
          },
          {
            "takenAt": "2026-09-20T20:21:10.289Z",
            "score": 0.5263728041838078,
            "side": "over",
            "mu": 45.971300182712966,
            "line": 46
          },
          {
            "takenAt": "2026-09-21T00:04:40.184Z",
            "score": 30.897328581647635,
            "side": "under",
            "mu": 45.60278806671699,
            "line": 46
          }
        ],
        "closingMu": 45.60278806671699,
        "closingLine": 46,
        "flaggedAt": "2026-09-21T00:04:40.184Z",
        "flaggedSide": "under",
        "flaggedScore": 30.897328581647635,
        "flaggedMu": 45.60278806671699,
        "flaggedLine": 46,
        "clv": null
      }
    }
  ]
};
