import type { DraftPick, Team } from '../types';
import { CURRENT_SEASON } from './leagueConstants';
import { TEAM_META } from './teamMeta';
import { SEEDED_ROSTERS } from './seededRosters';

// ---------------------------------------------------------------------------
// League data. Rosters/salaries come from the SalarySwish export (see
// seededRosters.ts, generated by scripts/build-seed.ts and verified to match
// each team's stated total). Draft capital is a neutral placeholder — each
// team's own future firsts — since the salary source doesn't include picks;
// trades are not reflected.
// ---------------------------------------------------------------------------

function defaultPicks(abbr: string): DraftPick[] {
  const picks: DraftPick[] = [];
  for (let year = CURRENT_SEASON; year <= CURRENT_SEASON + 7; year++) {
    picks.push({
      year,
      round: 1,
      originalTeam: abbr,
      notes: 'Own first-round pick (placeholder — trades not reflected)',
    });
  }
  picks.push({ year: CURRENT_SEASON, round: 2, originalTeam: abbr });
  picks.push({ year: CURRENT_SEASON + 1, round: 2, originalTeam: abbr });
  return picks;
}

export const TEAMS: Team[] = TEAM_META.map((m) => ({
  abbreviation: m.abbreviation,
  name: m.name,
  conference: m.conference,
  players: SEEDED_ROSTERS[m.abbreviation] ?? [],
  draftCapital: defaultPicks(m.abbreviation),
}));

const teamByAbbr = new Map(TEAMS.map((t) => [t.abbreviation, t]));

export function getTeam(abbr: string): Team {
  const t = teamByAbbr.get(abbr);
  if (!t) throw new Error(`Unknown team ${abbr}`);
  return t;
}
